### ISSUE TITLE
Cannot find default bot with username username_of_my_bot

### ISSUE THREAD

**Issue by sky1048576** [JungDev/django-telegrambot#11]
hello and thank you for your great job

I can work with this app with webhook method and it's working very well but i need to work with
polling method on my local app. then i went to my settings.py and changed MODE to POLLING
then i went to the root path and opened a terminal then i runed this command:
python manage.py botpolling --username konar19bot
but  i get this error:
`Cannot find default bot with username konar19bot
Bot not found`
but I an sure that there is a robot with this name I created it myself 
and something wired is this message : 
Required TELEGRAM_WEBHOOK_SITE missing in settings
why I have to difine TELEGRAM_WEBHOOK_SITE ? I don't want to set webhook. i just want to work with update method .

so can you tell where am I going wrong?
Do I have to do something more?

thank you

**Comment by JungDev** [comment]
I think your django didn't reload settings. May stop and restart django after settings changes and check if this problem is there yet.

**Comment by sky1048576** [comment]
yes that was the reason . 
i created another django app and i worked perfectly but how can I get rid of it?
in my primary project when I stopped django server and python manage.py runserver again and again but
still not working. 
how can I restart django server such in depth that django forgot about the past .
