### ISSUE TITLE
Should fail if app cannot be initalized

### ISSUE THREAD

**Issue by alephyud** [JungDev/django-telegrambot#13]
The app initializer catches all exceptions that happen during loading `telegrambot` modules in user apps, and only logs a `debug` message in case if import fails - until I looked at the [source code](https://github.com/JungDev/django-telegrambot/blob/master/django_telegrambot/apps.py#L221), I had to spend more than an hour to understand what was happening.

I think this at least merits an `error` log message (ideally, the Django app shouldn't even start if there is an error during initialization, but that change may be backwards-incompatible).

Happy to submit a pull request if you agree.

**Comment by JungDev** [comment]
You are right and thanks for help. If you want submit a pull request I will integrate it.
