### ISSUE TITLE
Telegram Version 12.0

### ISSUE THREAD

**Issue by maxatp** [JungDev/django-telegrambot#42]
How to make it compatible with Telegram Version 12.0

**Comment by lukruh** [comment]
There are some open pull requests that implement the new context approach of ptb 12, you can check that code changes if you want to fix it your self, or you can checkout my fork, where I fixed some Issues with newer PTB and django versions for my self:
https://github.com/telebotter/django-telegrambot

**Comment by maxatp** [comment]
Thanks a lot!
