### ISSUE TITLE
add management command for run bot in polling mode

### ISSUE THREAD

**Issue by AduchiMergen** [JungDev/django-telegrambot#5]
This usefully for debug bot on local dev environment.

like: https://github.com/peleccom/django-telegrambot/commit/51b733155fbcc157b3532d52ae1536c83acca611

**Comment by tapionx** [comment]
good idea!

**Comment by JungDev** [comment]
I'm working on a new version with a management command to run a polling mode update, but you must set mode in settings and then run the command. 
I think that use [ngrok](https://ngrok.com/) is a better and easy way to deploy a bot in local dev enviroment.

**Comment by JungDev** [comment]
Version 1.0.0 includes this feature, and is now available.
Be careful, because it's a major release, I've also changed bot's configuration by adding some new parameters. Check [README](https://github.com/JungDev/django-telegrambot/blob/master/README.rst)
